name: Release
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_release_draft:
    name: update release draft
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release_drafter.outputs.tag_name }}
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        with:
          commitish: main

  release:
    name: release
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    needs: update_release_draft
    steps:
      - uses: release-drafter/release-drafter@v5
        id: release-drafter
        with:
          publish: true
          commitish: main
